openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: 노트 CRUD를 위한 API 문서

servers:
  - url: http://localhost:3000

paths:
  /notes:
    post:
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteInput"
      responses:
        "201":
          description: 생성 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
    get:
      summary: 전체 노트 조회
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotesResponse"

  /notes/tag/{tag}:
    get:
      summary: 태그별 노트 조회
      parameters:
        - in: path
          name: tag
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotesResponse"

  /notes/{id}:
    put:
      summary: 노트 수정
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteInput"
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
        "404":
          description: 노트 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      summary: 노트 삭제
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 삭제 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "404":
          description: 노트 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        tag:
          type: string
    NoteInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        tag:
          type: string
      required:
        - title
        - content
        - tag
    NoteResponse:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: "#/components/schemas/Note"
    NotesResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/Note"
    MessageResponse:
      type: object
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
